### ISSUE TITLE
Sinusoid power compensation

### ISSUE THREAD

**Issue by bwpearre** [bwpearre/printimage#5]
Should modify beam power over resonant scan.

**Comment by Christos-Michas** [comment]
The pictures here are at 70%, which is far into the polymerization region. However notice that the color is uniform in the bottom picture.

Before compensation
![sinusoidal_power_compensation - after](https://cloud.githubusercontent.com/assets/11770083/25054203/cba1ebe6-2129-11e7-9a87-7bcf6e98ed03.PNG)

After compensation
![sinusoidal_power_compensation - before](https://cloud.githubusercontent.com/assets/11770083/25054204/cba2494c-2129-11e7-88fd-cc75297dd6cd.PNG)

Darker color means more polymerization, so more power deposition. Uniform color means uniform energy.
In addition, if you were to print the cube at 30%, the top picture would have shrinkage on the top and bottom edges of the cube, but not on the side edges. The bottom print would have the same amount of shrinkage on all directions.

**Comment by Christos-Michas** [comment]
5086e77d6ad27180f399084caadfbb386152502d
